version: '3.7'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=oas
      - POSTGRES_PASSWORD=Khan@1234

  api:
    build: .
    command: bash -c "python /app/api/manage.py migrate && python /app/api/manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
    volumes:
      - .:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db

  admin:
    build: ./frontend/admin
    command: npm start
    volumes:
      - './frontend/admin:/app/frontend'
      - node_modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  frontend:
    build: ./frontend/user
    command: npm start
    volumes:
      - './frontend/user:/app/user'
      - node_modules:/app/user/node_modules
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
  node_modules: