version: '3.7'

services:
  
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=oas
      - POSTGRES_PASSWORD=Khan@1234

  api:
    restart: unless-stopped
    build:
        context: .
        dockerfile: prod/Dockerfile
    # expose: 
    #   - 8000
    env_file: 
        - ./prod/.env
    environment:
      - DB_HOST=db
    command: gunicorn oas.wsgi:application --bind 0.0.0.0:8000
    volumes:
    #   - .:/app/api
      - staticFiles:/app/api/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  user:
    build:
        context: ./frontend/user
        dockerfile: Dockerfile.prod
    volumes:
        - react_static:/app/user/build/static
    # env_file: 
    #     - .env
    expose: 
      - 3000
    command: serve -s build -l 3000
    # ports:
    #   - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - api
    
  admin:
    build:
        context: ./frontend/admin
        dockerfile: Dockerfile.prod
    volumes:
        - react_admin_static:/app/frontend/build/static
    # env_file: 
    #     - .env
    command: serve -s build -l 3000
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - api
  
  nginx:
    restart: unless-stopped
    build: ./nginx
    volumes:
        - staticFiles:/app/api/static
        # - ./nginx/prod:/etc/nginx/conf.d/
        - react_static:/app/user/react_files/static
        - react_admin_static:/app/frontend/react_files/static
    ports:
        - 80:80
    depends_on:
      - user
      - admin

volumes:
  postgres_data:
  staticFiles:
  react_static:
  react_admin_static: