# Generated by Django 3.1.5 on 2021-04-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=191)),
                ('phone_number', models.CharField(blank=True, max_length=191, null=True)),
                ('status', models.CharField(blank=True, choices=[('FULFILLED', 'FULFILLED'), ('IN PROGRESS', 'IN PROGRESS'), ('CANCELLED', 'CANCELLED')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_customer', to='user.customer')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.country')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer')),
            ],
            options={
                'db_table': 'oas_enquiries',
                'ordering': ['part_number__part_number', 'company', 'email_address', 'phone_number', 'country__name', 'status', '-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('alt_part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=5, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('tag_date', models.CharField(blank=True, max_length=20, null=True)),
                ('turn_around_time', models.TextField(blank=True, null=True)),
                ('hazmat', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('un_code', models.CharField(blank=True, max_length=191, null=True)),
                ('stock_location', models.CharField(blank=True, max_length=191, null=True)),
                ('product_title', models.CharField(blank=True, max_length=191, null=True)),
                ('certification', models.TextField(blank=True, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=10, null=True)),
                ('unit_of_measure', models.CharField(blank=True, choices=[('CM', 'CM'), ('BOX', 'BOX'), ('KG', 'KG')], max_length=5, null=True)),
                ('hot_sale_item', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('product_image', models.ImageField(blank=True, max_length=191, null=True, upload_to='')),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_seller', models.BooleanField(default=False)),
                ('featured_product', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'oas_inventory',
                'ordering': ['quantity', 'product_title', 'description', 'condition', 'hazmat', 'unit_price', 'part_number', 'status', '-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oas_manufacturers',
                'ordering': ['name', 'slug', 'created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oas_product_category',
                'ordering': ['name', 'slug', 'created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.enquiry')),
                ('part_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
            ],
            options={
                'db_table': 'oas_productenquiries',
                'ordering': ['enquiry__status', 'part_number__part_number', '-created_at', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.manufacturer'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.supplier'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='part_number',
            field=models.ManyToManyField(through='inventory.ProductEnquiry', to='inventory.Inventory'),
        ),
    ]
