# Generated by Django 3.1.5 on 2021-04-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='hot_sale_item',
        ),
        migrations.AddField(
            model_name='inventory',
            name='daraz_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='daraz_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
