# Generated by Django 3.1.5 on 2021-04-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('inventory', '0002_auto_20210406_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_customer', to='user.customer'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.country'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(blank=True, choices=[('FULFILLED', 'FULFILLED'), ('IN PROGRESS', 'IN PROGRESS'), ('CANCELLED', 'CANCELLED')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.supplier'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='condition',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tag_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_of_measure',
            field=models.CharField(blank=True, choices=[('CM', 'CM'), ('BOX', 'BOX'), ('KG', 'KG')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productenquiry',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.enquiry'),
        ),
        migrations.AddField(
            model_name='productenquiry',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='part_number',
            field=models.ManyToManyField(through='inventory.ProductEnquiry', to='inventory.Inventory'),
        ),
    ]
