# Generated by Django 3.1.5 on 2021-04-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210410_0936'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimages',
            table='oas_product_images',
        ),
    ]
