# Generated by Django 3.1.5 on 2021-04-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_shopsetting_sliderimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimages',
            name='setting',
        ),
        migrations.DeleteModel(
            name='ShopSetting',
        ),
        migrations.DeleteModel(
            name='SliderImages',
        ),
    ]
