# Generated by Django 3.1.5 on 2021-04-19 11:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_productratings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRatings',
            new_name='ProductRating',
        ),
    ]
