# Generated by Django 3.1.5 on 2021-04-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210421_1051'),
        ('inventory', '0011_auto_20210421_1431'),
    ]

    operations = [
    ]
