# Generated by Django 3.1.5 on 2021-04-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventory_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='discounts',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
