# Generated by Django 3.1.5 on 2021-04-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, max_length=191, null=True, upload_to='logo')),
                ('featured_product', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oas_shop_setting',
            },
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sliders_img')),
            ],
            options={
                'db_table': 'oas_slider_images',
            },
        ),
    ]
