# Generated by Django 3.1.5 on 2021-04-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sliders',
            new_name='Slider',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider_title',
            new_name='title',
        ),
        migrations.AlterModelTable(
            name='slider',
            table='oas_slider',
        ),
    ]
