# Generated by Django 3.1.5 on 2021-04-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_setting', '0002_auto_20210416_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='btn_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='external_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
