# Generated by Django 3.1.5 on 2021-04-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_setting', '0003_auto_20210419_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='external_link',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
