# Generated by Django 3.1.5 on 2021-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_setting', '0004_auto_20210419_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='external_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
