# Generated by Django 3.1.5 on 2021-04-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_setting', '0005_auto_20210419_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='blog_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='email',
            field=models.EmailField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='phone_number',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
