# Generated by Django 3.1.5 on 2021-04-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_setting', '0006_auto_20210422_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='footer_tag_line',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
